### ISSUE TITLE
Seed local blockchain to reflect different stages of the issuance process

### ISSUE THREAD

**Issue by monitz87** [PolymathNetwork/polymath-apps#108]
The script that generates the local blockchain state and contracts should populate it with some more data to help us devs test different things without having to start over every time. This issue is intended as a reminder as well as a space to discuss what data we want.

From the top of my head I can think of:

- Some registered Tickers
- Some deployed SecurityTokens
- Some scheduled STOs
- Some minted tokens
- Some purchased tokens
- Some POLY supply

These should be distributed accross several accounts and when the script is finished it should print out which accounts have which assets to their name (and possibly which issuer URLs you have to navigate to for each particular interaction)

We shouldn't overdo it in terms of variety, since the more complicated interactions are covered by the core CLI.

Let me know what you think

**Comment by RafaelVidaurre** [comment]
One data-point to add is that we have a limit of 10 accounts. Unless ganache allows generating more?

**Comment by monitz87** [comment]
That would be worth looking into, but I think 10 is more than enough for now. Worst case we can have different seeds or a config file for the script to tweak which accounts get which assets

**Comment by maxsam4** [comment]
> One data-point to add is that we have a limit of 10 accounts. Unless ganache allows generating more?

Ganache does allow to generate more accounts. 10 is default but you can generate more.
