### ISSUE TITLE
App folder structure organisation

### ISSUE THREAD

**Issue by Grsmto** [PolymathNetwork/polymath-apps#16]
Hi guys,

Creating this issue to document/discuss the app structure for `polymath-issuer` and `polymath-ui` packages.

### Issuer
Regarding the issuer app, here is the structure I'm aiming for:

![screen shot 2018-09-25 at 14 59 00](https://user-images.githubusercontent.com/527559/46033038-9083f680-c0d3-11e8-8643-703bd0c5510f.jpg)

- `components/`
    - Here we have `layout/` components: like `<App>`, `<Root>`, ...
    - `utils/` any other components useful for the app itself but that can't be abstracted to the `polymath-ui` component library. For example in there we have `<NotFoundPage>`.
- `pages/`
We follow the `pages` pattern, that's usually there because of code-splitting and each `page` is an app entry chunk (in Next.js apps for example).
In there you have each page usually following the router structure. These are usually **container** components (linked to Redux store).
- Any setup/routing files can stay at the root.
- `style.scss` this file should have **only** global styles. Anything targeting a specific page/component is wrong and should be refactored (ie: everything in this file...).

### Component library (`polymath-ui`)
We move away from:
```
src/
  components/
  modules/
```

to 

```
src/
  components/
```

`modules/` is where the Redux connected components and their state are located.
"modules" doesn't mean anything here so it was hard to know where things should go. Instead we get every components in a single folder.
It can make sense for some components to export a Redux state but I think in most scenarios it should be avoided as much as possible as it binds them to Redux and forces user to use Redux.
The important thing is to have dumb reusable components. Ideally we should keep any "redux" components separated from the dumb component.

The goal is to get a `polymath-ui` component library that is:
- Reusable: I can take a component and get it working on different apps
- Composable: bigger components are composed of smaller other components

Observations: 
- Most of the code from `polymath-ui` is just there to share code between `polymath-issuer` and `polymath-investors`.
The problem is that some implementation details are "shared" whereas they shouldn't. It's pushing the DRY principle too far imo. `PolymathUI.js` component is a perfect example of that.

- Redux is mostly used as a global variable to communicate between packages. A lot of the Redux state could be replaced by props.

**Comment by RafaelVidaurre** [comment]
I agree to everything you've said here @Grsmto, go for it!
