### ISSUE TITLE
root babel.config.js is incorrect

### ISSUE THREAD

**Issue by Grsmto** [PolymathNetwork/polymath-apps#48]
- The root babel.config.js is actually wrong, it exports `moduleResolver` property but that’s a plugin.
So it should export `plugins: [ moduleResolverObjectHere ]` instead of a `moduleResolver` key.

- also every package seem to import that `moduleResolver` but only issuer/investor have the `babel-plugin-module-resolver` as dependency. They should all have it as dependency.

**Comment by RafaelVidaurre** [comment]
* Definitely agree with this, what we'd want is for it to export a list of plugins and just spread those into 
the package-specific config files.
* +1 as well.

This should be a fairly quick fix luckily
